"use client"

import { usePathname, useRouter } from 'next/navigation'
import { Anchor, Bell, CircleHelp, LogOut, User } from 'lucide-react'
import { incidents } from '@/services/mockData'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { AUTH_STORAGE_KEY } from '@/components/auth-guard'

export default function AuthorityHeader({ selectedId, onSelect }: { selectedId: string; onSelect: (id: string) => void }) {
  const router = useRouter(); const pathname = usePathname()
  const links = [{ href: '/', label: 'Spill Investigation' }, { href: '/attribution', label: 'Vessel Attribution' }]
  const changeIncident = (id: string) => { onSelect(id); router.replace(`${pathname}?incident=${encodeURIComponent(id)}`) }
  return <header className="border-b border-slate-200 bg-white text-slate-900"><div className="flex min-h-14 items-center justify-between gap-3 px-4 lg:px-6"><div className="flex shrink-0 items-center gap-3"><div className="flex size-8 items-center justify-center rounded-sm bg-[#0284c7] text-white"><Anchor className="size-4" /></div><div><div className="text-xs font-bold tracking-[0.14em]">MARISCOPE <span className="font-normal text-slate-400">/ MARITIME AUTHORITY</span></div><div className="hidden text-[9px] uppercase tracking-[0.18em] text-slate-500 sm:block">Operational geospatial intelligence portal</div></div></div><nav className="hidden items-center gap-1 lg:flex">{links.map(link => <a key={link.href} href={`${link.href}?incident=${encodeURIComponent(selectedId)}`} className={`border-b-2 px-3 py-4 text-[10px] font-bold uppercase tracking-wider ${pathname === link.href ? 'border-sky-600 text-slate-900' : 'border-transparent text-slate-500 hover:text-slate-900'}`}>{link.label}</a>)}</nav><div className="flex min-w-0 items-center gap-2 text-slate-500"><label className="hidden text-[9px] font-bold uppercase tracking-wider sm:block" htmlFor="incident-context">Active incident</label><select id="incident-context" value={selectedId} onChange={event => changeIncident(event.target.value)} className="max-w-[180px] border border-slate-300 bg-slate-50 px-2 py-1.5 font-mono text-[10px] text-slate-700 outline-none focus:border-sky-600"><option value="" disabled>Select incident</option>{incidents.map(incident => <option key={incident.id} value={incident.id}>{incident.id} · {incident.location}</option>)}</select><CircleHelp className="hidden size-4 lg:block" /><Bell className="hidden size-4 lg:block" /><DropdownMenu><DropdownMenuTrigger className="ml-1 flex size-8 items-center justify-center rounded-sm border border-slate-300 bg-slate-50 text-slate-600 hover:bg-slate-100"><User className="size-4" /></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuLabel>Analyst account</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onClick={() => { localStorage.removeItem(AUTH_STORAGE_KEY); router.push('/login') }}><LogOut /> Logout</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div><nav className="flex gap-1 overflow-x-auto border-t border-slate-200 px-4 lg:hidden">{links.map(link => <a key={link.href} href={`${link.href}?incident=${encodeURIComponent(selectedId)}`} className={`whitespace-nowrap border-b-2 px-3 py-2 text-[9px] font-bold uppercase tracking-wider ${pathname === link.href ? 'border-sky-600 text-slate-900' : 'border-transparent text-slate-500'}`}>{link.label}</a>)}</nav></header>
}
